server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: 99433900
    driver-class-name: org.postgresql.Driver
  #Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true